// Default insurance company contacts — Motor / Non Motor / Life
// Each entry is a separate email contact (one email per row)

export const DEFAULT_INSURANCE_COMPANIES = [

  // ── LIFE ────────────────────────────────────────────────────────────────────
  { name:'Continental Life',   email:'shehank@cilankalife.com',             category:'Life' },
  { name:'Continental Life',   email:'lifeunderwriting@cilankalife.com',    category:'Life' },
  { name:'LOLC Life',          email:'ShashimaT@lolcgeneral.com',           category:'Life' },
  { name:'Ceylinco Life',      email:'gayanv@ceylife.lk',                   category:'Life' },
  { name:'SLIC Life',          email:'sathyanjaleet@sliclife.com',          category:'Life' },
  { name:'SLIC Life',          email:'kalpar@sliclife.com',                 category:'Life' },
  { name:'HNB Assurance',      email:'asanka.gonagala@hnblife.lk',          category:'Life' },
  { name:'HNB Assurance',      email:'dunila.fernando@hnblife.lk',          category:'Life' },
  { name:'HNB Assurance',      email:'ruwanya.wi@hnblife.lk',               category:'Life' },
  { name:'Sanasa Life',        email:'achinisenadeera@sicl.com',            category:'Life' },
  { name:'Union Assurance',    email:'praneeth@unionassurance.com',         category:'Life' },
  { name:'Softlogic Life',     email:'dileepa.fernando@softlogiclife.lk',   category:'Life' },
  { name:'Softlogic Life',     email:'Imesha.DeMel@softlogiclife.lk',       category:'Life' },
  { name:'Softlogic Life',     email:'dilshan.gunawardena@softlogiclife.lk',category:'Life' },
  { name:'AIA Insurance',      email:'suren.mallikahewa@aia.com',           category:'Life' },
  { name:'AIA Insurance',      email:'ruvini.kaushalya@aia.com',            category:'Life' },
  { name:'Janashakthi Life',   email:'chamathg@janashakthi.com',            category:'Life' },
  { name:'Amana Life',         email:'gothami.rathnayaka@takaful.lk',       category:'Life' },

  // ── NON MOTOR ────────────────────────────────────────────────────────────────
  { name:'Continental',        email:'charithm@cilanka.com',                          category:'Non Motor' },
  { name:'LOLC General',       email:'ErandiSa@lolcgeneral.com',                      category:'Non Motor' },
  { name:'LOLC General',       email:'broker_uw@lolcgeneral.com',                     category:'Non Motor' },
  { name:'LOLC General',       email:'ShashimaT@lolcgeneral.com',                     category:'Non Motor' },
  { name:'Orient Insurance',   email:'Nimanthi.Jayasinghe@orientinsurance.lk',        category:'Non Motor' },
  { name:'Orient Insurance',   email:'Sanjaya.Rajapakshe@orientinsurance.lk',         category:'Non Motor' },
  { name:'Orient Insurance',   email:'Finolla.Outschoorn@orientinsurance.lk',         category:'Non Motor' },
  { name:'Orient Insurance',   email:'quotations.nonmotor@orientinsurance.lk',        category:'Non Motor' },
  { name:'Amana Takaful',      email:'ashan.mihiranga@takaful.lk',                    category:'Non Motor' },
  { name:'Peoples Insurance',  email:'nishets@peoplesinsurance.lk',                   category:'Non Motor' },
  { name:'Ceylinco General',   email:'venura.priyasad@gmail.com',                     category:'Non Motor' },
  { name:'Ceylinco General',   email:'venura_p@ceyins.lk',                            category:'Non Motor' },
  { name:'Ceylinco General',   email:'vipclaim3@ceyins.lk',                           category:'Non Motor' },
  { name:'Ceylinco General',   email:'viposhanthi@ceyins.lk',                         category:'Non Motor' },
  { name:'Sri Lanka Insurance',email:'nilukam@slicgeneral.com',                       category:'Non Motor' },
  { name:'Fairfirst Insurance',email:'geethd@fairfirst.lk',                           category:'Non Motor' },
  { name:'Allianz Insurance',  email:'bovazw@allianz.lk',                             category:'Non Motor' },
  { name:'Allianz Insurance',  email:'menakag@allianz.lk',                            category:'Non Motor' },
  { name:'HNB General',        email:'prasad.rodrigo@hnbgeneral.com',                 category:'Non Motor' },
  { name:'HNB General',        email:'madhusanka.fonseka@hnbgeneral.com',             category:'Non Motor' },
  { name:'HNB General',        email:'hasintha.arachchige@hnbgeneral.com',            category:'Non Motor' },
  { name:'Sanasa SGIC',        email:'quotationnonmotor@sgic.lk',                     category:'Non Motor' },
  { name:'Sanasa SGIC',        email:'rohanj@sgic.lk',                                category:'Non Motor' },
  { name:'Sanasa SGIC',        email:'sachith@sgic.lk',                               category:'Non Motor' },
  { name:'Sanasa SGIC',        email:'dushmi@sgic.lk',                                category:'Non Motor' },
  { name:'Sanasa SGIC',        email:'harshal@sgic.lk',                               category:'Non Motor' },
  { name:'Co-op Insurance',    email:'mahesh.w@coopinsu.com',                         category:'Non Motor' },
  { name:'Co-op Insurance',    email:'ishara.u@coopinsu.com',                         category:'Non Motor' },

  // ── MOTOR ────────────────────────────────────────────────────────────────────
  { name:'Continental',        email:'charithm@cilanka.com',                          category:'Motor' },
  { name:'Continental',        email:'broker.motor@cilanka.com',                      category:'Motor' },
  { name:'LOLC General',       email:'ShashimaT@lolcgeneral.com',                     category:'Motor' },
  { name:'LOLC General',       email:'Broker_UW@lolcgeneral.com',                     category:'Motor' },
  { name:'Orient Insurance',   email:'Orient.Motorquotation@orientinsurance.lk',      category:'Motor' },
  { name:'Orient Insurance',   email:'Sanjaya.Rajapakshe@orientinsurance.lk',         category:'Motor' },
  { name:'Orient Insurance',   email:'Nimanthi.Jayasinghe@orientinsurance.lk',        category:'Motor' },
  { name:'Amana Takaful',      email:'ashan.mihiranga@takaful.lk',                    category:'Motor' },
  { name:'Peoples Insurance',  email:'nishets@peoplesinsurance.lk',                   category:'Motor' },
  { name:'Peoples Insurance',  email:'imashaf@peoplesinsurance.lk',                   category:'Motor' },
  { name:'Peoples Insurance',  email:'tharushis@peoplesinsurance.lk',                 category:'Motor' },
  { name:'Ceylinco General',   email:'venura_p@ceyins.lk',                            category:'Motor' },
  { name:'Ceylinco General',   email:'janakak@ceyins.lk',                             category:'Motor' },
  { name:'Sri Lanka Insurance',email:'malship@slicgeneral.com',                       category:'Motor' },
  { name:'Sri Lanka Insurance',email:'pathumt@slicgeneral.com',                       category:'Motor' },
  { name:'Fairfirst Insurance',email:'harshanak@fairfirst.lk',                        category:'Motor' },
  { name:'Fairfirst Insurance',email:'danushkac@fairfirst.lk',                        category:'Motor' },
  { name:'Allianz Insurance',  email:'MenakaG@allianz.lk',                            category:'Motor' },
  { name:'Allianz Insurance',  email:'Bovazw@allianz.lk',                             category:'Motor' },
  { name:'Allianz Insurance',  email:'brokerquotations@allianz.lk',                   category:'Motor' },
  { name:'HNB GI',             email:'prasad.rodrigo@hnbgeneral.com',                 category:'Motor' },
  { name:'HNB GI',             email:'madhusanka.fonseka@hnbgeneral.com',             category:'Motor' },
  { name:'HNB GI',             email:'hasintha.arachchige@hnbgeneral.com',            category:'Motor' },
  { name:'HNB GI',             email:'cq.unit@hnbgeneral.com',                        category:'Motor' },
  { name:'Sanasa SGIC',        email:'sachith@sgic.lk',                               category:'Motor' },
  { name:'Sanasa SGIC',        email:'harshal@sgic.lk',                               category:'Motor' },
  { name:'Sanasa SGIC',        email:'dushmi@sgic.lk',                                category:'Motor' },
  { name:'Co-op Insurance',    email:'mahesh.w@coopinsu.com',                         category:'Motor' },
  { name:'Co-op Insurance',    email:'ishara.u@coopinsu.com',                         category:'Motor' },
];

export const COMPANY_CATEGORIES = ['Motor', 'Non Motor', 'Life'];

export const CATEGORY_COLORS = {
  'Motor':     { bg:'rgba(59,130,246,0.10)',  color:'#2563eb',  border:'rgba(59,130,246,0.25)'  },
  'Non Motor': { bg:'rgba(16,185,129,0.10)', color:'#059669',  border:'rgba(16,185,129,0.25)'  },
  'Life':      { bg:'rgba(139,92,246,0.10)', color:'#7c3aed',  border:'rgba(139,92,246,0.25)'  },
};
